# This example shows how to define a deployment.
# Syntactically, it is same as defining ReplicaSet except the kind.
# But, there is a difference when updating the deployment.
# Detailed difference will be explained in echo-deployment-v2.yaml.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo
      tier: app
  template:
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echo
          image: "ghcr.io/subicura/echo:v1"