# This example shows how to set strategy for deployment.
# In this example, RollingUpdate strategy is used.
# The number of pods to be updated can be set.
# If not set, the default is 25% of replicas.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy-st
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo
      tier: app
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
  template:
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echo
          image: "ghcr.io/subicura/echo:v1"
          livenessProbe:
            httpGet:
              path: /
              port: 3000