# This example shows how ReplicaSet is defined.
# Pods are identified by their labels.
# If the number of Pods does not match the number of replicas,
# ReplicaSetController will create/terminate Pods.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
      tier: app
  template:
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echo
          image: "ghcr.io/subicura/echo:v1"